apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-account
  labels:
    app: service-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-account
  template:
    metadata:
      labels:
        app: service-account
    spec:
      containers:
      - name: app-account
        image: stivid007/nodejs-account:2
        ports:
        - containerPort: 5002
        env:
        - name: NACOS_SERVERADDR
          value: "164.90.255.230:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-account
spec:
  type: LoadBalancer
  selector:
    app: service-account
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
    name: http